sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: osx
      language: generic
      python: 2.7

install:
  - pip install tox-travis
script: tox
notifications:
  email: false
branches:
  only:
    - master
