sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: osx
      language: generic
      python: 2.7
jobs:
  include:
    - stage: release-test
      script: RELEASE_SKIP=head PYVER=2.7 ./release-test.sh && RELEASE_SKIP=head PYVER=3 ./release-test.sh
install:
  - pip2 install tox-travis || pip3 install tox-travis
script: tox
notifications:
  email: false
branches:
  only:
    - master
